su_account:
    resource: "@SUAccountBundle/Resources/config/routing.yml"
    prefix:   /

su_user:
    resource: "@SUUserBundle/Resources/config/routing.yml"
    prefix:   /

su_main:
    resource: "@SUMainBundle/Resources/config/routing.yml"
    prefix:   /
