# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        SU\UserBundle\Entity\User: sha512

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:         ^/
            anonymous:       true
            provider:        main
            form_login:
                login_path:  /login
                check_path:  /login_check
                remember_me: true
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:        /logout
                target:      /
            remember_me:
                secret:         %secret%
            logout: true
    
    access_control:
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_USER }