su_account_homepage:
    path:     /home
    defaults: { _controller: SUAccountBundle:Account:home }

su_account_send_category:
    path:     /home/sendCategory
    defaults: { _controller: SUAccountBundle:Account:sendCategory }

su_account_delete_category:
    path:     /home/deleteCategory
    defaults: { _controller: SUAccountBundle:Account:deleteCategory }

su_account_mobile_immediate:
    path:     /home/mimmediate
    defaults: { _controller: SUAccountBundle:Account:mimmediate }

su_account_send_immediate:
    path:     /home/sendImmediate
    defaults: { _controller: SUAccountBundle:Account:sendImmediate }

su_account_mobile_differed:
    path:     /home/mdiffered
    defaults: { _controller: SUAccountBundle:Account:mdiffered }

su_account_mobile_systematic:
    path:     /home/msystematic
    defaults: { _controller: SUAccountBundle:Account:msystematic }

su_account_mobile_account:
    path:     /home/maccount
    defaults: { _controller: SUAccountBundle:Account:maccount }

su_account_new_account:
    path:     /home/newAccount
    defaults: { _controller: SUAccountBundle:Account:newAccount }

su_account_send_new_account:
    path:     /home/sendNewAccount
    defaults: { _controller: SUAccountBundle:Account:sendNewAccount }

su_account_update_principal_ac:
    path:     /home/updateAcPriority
    defaults: { _controller: SUAccountBundle:Account:updateAcPriority }

su_account_update_first_amount:
    path:     /home/updateFirstAmount
    defaults: { _controller: SUAccountBundle:Account:updateFirstAmount }

su_account_delete_account:
    path:     /home/deleteAccount
    defaults: { _controller: SUAccountBundle:Account:deleteAccount }

su_account_send_operation:
    path:     /home/sendOperation
    defaults: { _controller: SUAccountBundle:Account:sendOperation }

su_account_month_operations:
    path:     /home/monthOperations/{pdf}/{date}
    defaults:
        _controller: SUAccountBundle:Account:getMonthOperations
        pdf: 0
        date: "-1"

su_account_future_operations:
    path:     /home/futureOperations/{pdf}/{date}
    defaults:
        _controller: SUAccountBundle:Account:getFutureOperations
        pdf: 0
        date: "-1"

su_account_graph_data:
    path:     /home/graphData
    defaults: { _controller: SUAccountBundle:Account:getGraphData }

su_account_operation_update:
    path:     /home/updateOperation
    defaults: { _controller: SUAccountBundle:Account:updateOperation }

su_account_delete_operation:
    path:     /home/deleteOperation
    defaults: { _controller: SUAccountBundle:Account:deleteOperation }

su_account_category_details:
    path:     /home/categoryDetails
    defaults: { _controller: SUAccountBundle:Account:categoryDetails }

su_account_pdf:
    path:     /home/pdf/{year}/{month}
    defaults: { _controller: SUAccountBundle:Account:pdf }
    requirements:
        year: \d{4}
        month: \d{2}

su_account_cover:
    path:     /home/cover
    defaults: { _controller: SUAccountBundle:Account:cover }

su_account_account_template:
    path:     /home/accountTemplate
    defaults: { _controller: SUAccountBundle:Account:accountTemplate }

su_account_graph_template:
    path:     /home/graphTemplate
    defaults: { _controller: SUAccountBundle:Account:graphTemplate }

su_account_refresh_account:
    path:     /home/refresh
    defaults: { _controller: SUAccountBundle:Account:refreshAccount }