su_account_homepage:
    path:     /home
    defaults: { _controller: SUAccountBundle:Account:home }

su_account_send_category:
    path:     /home/sendCategory
    defaults: { _controller: SUAccountBundle:Account:sendCategory }

su_account_delete_category:
    path:     /home/deleteCategory
    defaults: { _controller: SUAccountBundle:Account:deleteCategory }

su_account_mobile_immediate:
    path:     /home/mimmediate
    defaults: { _controller: SUAccountBundle:Account:mimmediate }

su_account_send_immediate:
    path:     /home/sendImmediate
    defaults: { _controller: SUAccountBundle:Account:sendImmediate }

su_account_mobile_differed:
    path:     /home/mdiffered
    defaults: { _controller: SUAccountBundle:Account:mdiffered }

su_account_mobile_systematic:
    path:     /home/msystematic
    defaults: { _controller: SUAccountBundle:Account:msystematic }

su_account_mobile_account:
    path:     /home/maccount
    defaults: { _controller: SUAccountBundle:Account:maccount }

su_account_new_account:
    path:     /home/newAccount
    defaults: { _controller: SUAccountBundle:Account:newAccount }

su_account_send_new_account:
    path:     /home/sendNewAccount
    defaults: { _controller: SUAccountBundle:Account:sendNewAccount }

su_account_update_principal_ac:
    path:     /home/updateAcPriority
    defaults: { _controller: SUAccountBundle:Account:updateAcPriority }

su_account_update_first_amount:
    path:     /home/updateFirstAmount
    defaults: { _controller: SUAccountBundle:Account:updateFirstAmount }

su_account_delete_account:
    path:     /home/deleteAccount
    defaults: { _controller: SUAccountBundle:Account:deleteAccount }

su_account_send_operation:
    path:     /home/sendOperation
    defaults: { _controller: SUAccountBundle:Account:sendOperation }

su_account_month_operations:
    path:     /home/monthOperations
    defaults: { _controller: SUAccountBundle:Account:getMonthOperations }

su_account_future_operations:
    path:     /home/futureOperations
    defaults: { _controller: SUAccountBundle:Account:getFutureOperations }

su_account_graph_data:
    path:     /home/graphData
    defaults: { _controller: SUAccountBundle:Account:getGraphData }

su_account_operation_update:
    path:     /home/updateOperation
    defaults: { _controller: SUAccountBundle:Account:updateOperation }

su_account_delete_operation:
    path:     /home/deleteOperation
    defaults: { _controller: SUAccountBundle:Account:deleteOperation }

su_account_category_details:
    path:     /home/categoryDetails
    defaults: { _controller: SUAccountBundle:Account:categoryDetails }

su_account_pdf:
    path:     /home/pdf
    defaults: { _controller: SUAccountBundle:Account:pdf }