su_account_homepage:
    path:     /home
    defaults: { _controller: SUAccountBundle:Account:home }

su_account_send_category:
    path:     /home/sendCategory
    defaults: { _controller: SUAccountBundle:Account:sendCategory }

su_account_delete_category:
    path:     /home/deleteCategory
    defaults: { _controller: SUAccountBundle:Account:deleteCategory }

su_account_mobile_immediate:
    path:     /home/mimmediate
    defaults: { _controller: SUAccountBundle:Account:mimmediate }

su_account_send_immediate:
    path:     /home/sendImmediate
    defaults: { _controller: SUAccountBundle:Account:sendImmediate }

su_account_mobile_differed:
    path:     /home/mdiffered
    defaults: { _controller: SUAccountBundle:Account:mdiffered }

su_account_mobile_systematic:
    path:     /home/msystematic
    defaults: { _controller: SUAccountBundle:Account:msystematic }

su_account_mobile_account:
    path:     /home/maccount
    defaults: { _controller: SUAccountBundle:Account:maccount }

su_account_new_account:
    path:     /home/newAccount
    defaults: { _controller: SUAccountBundle:Account:newAccount }

su_account_send_new_account:
    path:     /home/sendNewAccount
    defaults: { _controller: SUAccountBundle:Account:sendNewAccount }

su_account_update_principal_ac:
    path:     /home/updateAcPriority
    defaults: { _controller: SUAccountBundle:Account:updateAcPriority }

su_account_delete_account:
    path:     /home/deleteAccount
    defaults: { _controller: SUAccountBundle:Account:deleteAccount }