services:
    su_account.categoryService:
        class: SU\AccountBundle\CategoryService\SUCategoryService
        arguments: ['@service_container']
    su_account.accountService:
        class: SU\AccountBundle\AccountService\SUAccountService
        arguments: ['@service_container']